variables:
  buildConfiguration: 'Release'  

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.500'
  inputs:
    version: 2.1.500

- powershell: |
   $installedTools = dotnet tool list --global
   if ( ![bool]($installedTools -match "dotnet-sonarscanner"))
   {
        dotnet tool install --global dotnet-sonarscanner 
   }
   else
   {
        Write-Host "SonarScanner already installed. Skipping installation."
   }
   if ( ![bool]($installedTools -match "dotnet-reportgenerator-globaltool"))
   {
       dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
   }
   else
   {
        Write-Host "ReportGenerator already installed. Skipping installation."
   }
  displayName: 'Install Sonar Scanner and ReportGenerator'

- script: |
    dotnet restore
    dotnet sonarscanner begin /k:"WouterDeKort_Utopia" /o:"wouterdekort-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(Sonar.Login)" /d:sonar.global.exclusions="wwwroot/lib/**" /d:sonar.branch.name="$(Build.SourceBranchName)" /d:sonar.cs.opencover.reportsPaths="tests\ToDo.Tests\coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs""
    dotnet build --configuration $(BuildConfiguration)
    dotnet test **/*Tests/*.csproj --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    dotnet sonarscanner end /d:sonar.login="$(Sonar.Login)"
    dotnet publish src\ToDo.Web\ToDo.Web.csproj --configuration $(BuildConfiguration) --output ToDo.Web
  displayName: 'Build and test'

- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@18
  displayName: 'WhiteSource Bolt'
  inputs:
    cwd: src
    advance: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: drop