variables:
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Build.SourcesDirectory)/packages
  keyfile: '**/*.csproj, salt.txt'
  azureDevOpsArtifactsFeed: 'c013416d-862f-4a53-b537-3724f44e435c'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.500'
  inputs:
    version: 2.1.500

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- powershell: |
   $installedTools = dotnet tool list --global
   if ( ![bool]($installedTools -match "dotnet-sonarscanner"))
   {
        dotnet tool install --global dotnet-sonarscanner 
   }
   else
   {
        Write-Host "SonarScanner already installed. Skipping installation."
   }
  displayName: 'Install Sonar Scanner'

- script: dotnet sonarscanner begin /k:"WouterDeKort_Utopia" /o:"wouterdekort-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(Sonar.Login)" /d:sonar.global.exclusions="wwwroot/lib/**" /d:sonar.branch.name="$(Build.SourceBranchName)"
  displayName: 'Begin Sonar Scan'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    arguments: '--configuration $(BuildConfiguration)'

- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@18
  displayName: 'WhiteSource Bolt'
  inputs:
    cwd: src
    advance: true

- script: dotnet sonarscanner end /d:sonar.login="$(Sonar.Login)"
  displayName: 'End Sonar Scan'
     
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    projects: 'src/Todo.Web/ToDo.Web.csproj'
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: drop